@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Telemetry Service - Component Diagram

Container_Ext(temperatureService, "Temperature API", "Service", "Gets sensors' temperature")

Container(telemetryService, "Telemetry Service") {
    Component(telemetryApi, "Telemetry API Controller", "REST API", "Handles HTTP requests for telemetry data retrieval")
    Component(telemetryCollector, "Telemetry Collector", "Background Service", "Collects telemetry data via Device Management Service")
    Component(telemetryProcessor, "Telemetry Processor", "Business Logic", "Processes and validates telemetry data")
    Component(telemetryRepository, "Telemetry Repository", "Data Access", "CRUD operations for telemetry data")
}

Container(APIGateway, "APIGateway", "AGW", "API router")

ContainerDb(telemetryDb, "Telemetry Database", "PostgreSQL", "Stores telemetry data")
Rel(telemetryApi, telemetryRepository, "Queries telemetry data")

Rel(APIGateway, telemetryApi, "Request telemetry data")
Rel(telemetryCollector, temperatureService, "Collects telemetry data", "HTTP/gRPC")
Rel(telemetryCollector, telemetryProcessor, "Sends raw telemetry")
Rel(telemetryProcessor, telemetryRepository, "Stores processed telemetry")

Rel(telemetryRepository, telemetryDb, "CRUD operations")

@enduml
